dataset:
  root_path: "./kitti"
  image_path: "image_00"
  velodyne_only: No
  velo_path: "velodyne_points"
  label_path: "labels"
  log_name: "log.pkl"
  label_type: "txt"
  resume: Yes
  step: 10
  pointcloud_reader:
   transform: Yes
   calib_path: "./kitti/calib"
   color: "red"
  image_reader:
   type: "png"

displayer:
 mode: "annotation"
 window_size:
# max size
  - 1200
  - 800
 img:
   view_port:
    - 0
    - 0.5
    - 1.0
    - 1.0
   bg:
    - 0.1
    - 0.2
    - 0.4
 pc:
   view_port:
    - 0
    - 0
    - 1.0
    - 0.5
 selection:
   debug: No

 auto_save: Yes
