dataset:
 resume: Yes
 velodyne_only: No
 label_path: "gts"
 num_classes: 10
 classes:
  - "Car"
  - "Pedestrian"
  - "Cyclist"
 # pointcloud_reader:
  # transform: No

 # prefix_name: "002773"
 # filter_classes:
  # - "Car"
displayer:
 img_bg:
  - 0.1
  - 0.2
  - 0.7
 # pc:
  # view_port:
   # - 0.0
   # - 0.0
   # - 1.0
   # - 1.0
 mode: "display"
 auto_save: Yes
