dataset:
 resume: No
 velodyne_only: Yes
 velo_path: "merge"
 # label_path: "merge"
 pointcloud_reader:
  transform: No

 # prefix_name: "merge_1525918800"
 # filter_classes:
  # - "Car"
displayer:
 img_bg:
  - 0.1
  - 0.2
  - 0.7
 pc:
  view_port:
   - 0.0
   - 0.0
   - 1.0
   - 1.0
 mode: "annotation"
 auto_save: Yes
