dataset:
 resume: Yes
 velodyne_only: Yes
 velo_path: "lidar"

 pointcloud_reader:
  transform: No

 # prefix_name: "merge_1525918800"
 # filter_classes:
  # - "Car"
displayer:
 img_bg:
  - 0.1
  - 0.2
  - 0.7
 classes_colors_map:
  - [0, 255, 0]
  - [0,0,255]
  - [0,51,113]
  - [255,0,255]
  - [0.54,0.4117,0.078]
 pc:
  view_port:
   - 0.0
   - 0.0
   - 1.0
   - 1.0
 mode: "annotation"
 auto_save: Yes
